# Generated by Django 5.2.6 on 2026-01-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('hygiene', 'Hygiene & Personal Care'), ('snacks', 'Snacks'), ('electronics', 'Electronic Products'), ('drawing', 'Drawing & Painting'), ('frozen', 'Frozen Food'), ('wellness', 'Sexual Wellness Products'), ('medical', 'Medical Products')], default='groceries', max_length=20),
        ),
    ]
